#cloud-config
runcmd:
  - apt-get update
  - apt-get install -y docker.io docker-compose-v2 postgresql-client
  - systemctl enable --now docker
  - mkdir -p containers/prefect_data
  - mkdir -p containers/caddy
