services:
  caddy:
    image: caddy:latest
    container_name: caddy
    environment:
      PUBLIC_HOST: ${PUBLIC_HOST}
    volumes:
      - ${HOME}/containers/caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - internal-network
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    networks:
      - internal-network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      - caddy

  prefect-server:
    image: prefecthq/prefect:3-latest
    container_name: prefect
    networks:
      - internal-network
    depends_on:
      - caddy
      - redis
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: "postgresql+asyncpg://prefect:prefect@${PREFECT_API_DATABASE_CONNECTION_HOST}/prefect"
      PREFECT_SERVER_API_HOST: 0.0.0.0
      PREFECT_SERVER_UI_API_URL: "https://${PUBLIC_HOST}/api"
      PREFECT_SERVER_API_AUTH_STRING: "admin:${PREFECT_PASSWORD}"
      PREFECT_MESSAGING_BROKER: prefect_redis.messaging
      PREFECT_MESSAGING_CACHE: prefect_redis.messaging
      PREFECT_REDIS_MESSAGING_HOST: redis
      PREFECT_REDIS_MESSAGING_PORT: 6379
      PREFECT_REDIS_MESSAGING_DB: 0
    command: prefect server start
    volumes:
      - $HOME/container_data/prefect_data
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request as u; u.urlopen('https://${PUBLIC_HOST}/api/health', timeout=1)",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  redis_data:

networks:
  internal-network:
    driver: bridge
    name: internal-network
